### ISSUE TITLE
Change color of thumb-y

### ISSUE THREAD

**Issue by iscorporacion** [ehsan-shv/react-nice-scroll#4]
Hi, how can i change thumb color from component?

**Comment by ehsan-shv** [comment]
Hi! What do you mean by "thumb"?

**Comment by iscorporacion** [comment]
the color of the scrollbar, I can do something like <ScrollContainer color=red>, I need several scrolls but they have a different color in each component

**Comment by ehsan-shv** [comment]
Just change the style:
```css
.scrollbar-thumb-y {
 background: #000
}
```
Several scrollbars:
Wrap the container component with a wrapper element and change the style
```css
.wrapper .scrollbar-thumb-y {
 background: #000
}
```
